### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by mehyaz** [ZaidRaza26/ZSlider#1]
Hello, can you add sample code of project in the gif which has on-off button.

**Comment by ZaidRaza26** [comment]
Umm, sure.
I'll send you tomorrow.

**Comment by ZaidRaza26** [comment]
import SwiftUI

    struct ContentView: View {
    
    init(Height:CGFloat, filledHeight: CGFloat, filledColor: [Color], unfilledColor: [Color]) {
        self.outerHeight = Height
        self.sliderHeight = outerHeight * filledHeight
        self.filledColor = filledColor
        self.unfilledColor = unfilledColor
    }
    
    @State private var sliderHeight: CGFloat = 250.0
    var outerHeight: CGFloat = 500.0
    @State private var isOn = true
    @State private var result = 0.5
    
    
    var filledColor: [Color] = []
    var unfilledColor: [Color] = []
    
    var simpleDrag: some Gesture {
        DragGesture()
            .onChanged { value in
                if value.location.y > outerHeight {
                    result = 0.0
                }
                else if value.location.y < 0 {
                    result = 1.0
                }
                else {
                    withAnimation(){
                    result = 1.0 - Double(value.location.y / outerHeight)
                }
                }
                withAnimation{
                    self.sliderHeight = value.location.y
                }
            }
    }
    
    var body: some View {
        GeometryReader { geometry in
            ZStack {
                LinearGradient(gradient: Gradient(colors: [Color(red: 7/255, green: 15/255, blue: 43/255), Color(red: 60/255, green: 69/255, blue: 94/255)]), startPoint: .bottomTrailing, endPoint: .topLeading)
                VStack(spacing: 40){
                    if isOn {
                        Text("Volume")
                            .gradientForeground(colors: [Color(red: 110/255, green: 110/255, blue: 185/255), Color(red: 93/255, green: 145/255, blue: 190/255)])
                            .font(Font.custom("Raleway-Thin", size: 40))
                        Text("\(Int (result * 100))")
                            .gradientForeground(colors: [Color(red: 110/255, green: 110/255, blue: 185/255), Color(red: 93/255, green: 145/255, blue: 190/255), Color(red: 113/255, green: 180/255, blue: 178/255), Color(red: 185/255, green: 204/255, blue: 126/255)])
                            .font(Font.custom("Raleway-Thin", size: 80))
                    }
                    else {
                        Text("Volume")
                            .gradientForeground(colors: [Color(red: 80/255, green: 64/255, blue: 94/255)])
                            .font(Font.custom("Raleway-Thin", size: 40))
                        Text("\(Int (result * 100))")
                            .gradientForeground(colors: [Color(red: 80/255, green: 64/255, blue: 94/255)])
                            .font(Font.custom("Raleway-Thin", size: 80))
                            
                    }
                    VStack(){
                        ZStack(alignment: .top){
                            
                            if isOn {
                                LinearGradient(gradient: Gradient(colors: [Color(red: 110/255, green: 110/255, blue: 185/255), Color(red: 93/255, green: 145/255, blue: 190/255), Color(red: 113/255, green: 180/255, blue: 178/255), Color(red: 185/255, green: 204/255, blue: 126/255)]), startPoint: .bottom, endPoint: .top).frame(width: 200, height: 500)
                                LinearGradient(gradient: Gradient(colors: [Color(red: 83/255, green: 92/255, blue: 118/255)]), startPoint: .bottom, endPoint: .top).frame(maxWidth: 200, maxHeight: sliderHeight)
                            }
                            else {
                                LinearGradient(gradient: Gradient(colors: [Color(red: 55/255, green: 64/255, blue: 94/255)]), startPoint: .bottom, endPoint: .top).frame(width: 200, height: 500)
                                LinearGradient(gradient: Gradient(colors: [Color(red: 83/255, green: 92/255, blue: 118/255)]), startPoint: .bottom, endPoint: .top).frame(maxWidth: 200, maxHeight: sliderHeight)
                                    .opacity(0.2)
                            }
                        }
                    }
                    .frame(width: 200, height: 500)
                    .cornerRadius(50)
                    .gesture(
                        simpleDrag
                    )
                    .allowsHitTesting(isOn)
                    HStack(spacing: 50) {
                        Circle()
                            .gradientForeground(colors: [Color(red: 110/255, green: 110/255, blue: 185/255), Color(red: 93/255, green: 145/255, blue: 190/255), Color(red: 113/255, green: 180/255, blue: 178/255), Color(red: 185/255, green: 204/255, blue: 126/255)])
                            .frame(width: 20, height: 20)
                        ZStack{
                            
                            Circle()
                                
                                .frame(width: 80, height: 80)
                                .gradientForeground(colors: [Color(red: 110/255, green: 110/255, blue: 185/255), Color(red: 93/255, green: 145/255, blue: 190/255), Color(red: 113/255, green: 180/255, blue: 178/255)])
                            
                            Image(isOn ? "on" : "off")
                                .resizable()
                                .frame(width: 40, height: 40, alignment: .center)
                            
                        }
                        .scaleEffect(isOn ? 1 : 1.1)
                        .animation(.interpolatingSpring(stiffness: 50, damping: 10, initialVelocity: 10))
                        .onTapGesture {
                            self.isOn.toggle()
                        }
                        
                        
                        Circle()
                            .frame(width: 20, height: 20)
                            .gradientForeground(colors: [Color(red: 110/255, green: 110/255, blue: 185/255), Color(red: 93/255, green: 145/255, blue: 190/255), Color(red: 113/255, green: 180/255, blue: 178/255), Color(red: 185/255, green: 204/255, blue: 126/255)])
                    }
                }
            }
            .edgesIgnoringSafeArea(.all)
        }
    }
    }

    extension View {
    public func gradientForeground(colors: [Color]) -> some View {
        self.overlay(LinearGradient(gradient: .init(colors: colors),
                                    startPoint: .topLeading,
                                    endPoint: .bottomTrailing))
            .mask(self)
       }
    }
